// app/layout.tsx
import './globals.css' // global styles import
import { ReactNode } from 'react'

export const metadata = {
  title: 'Career Helper Agent',
  description: 'Your AI-powered career guide!', // site ka SEO title aur description
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-purple-100 to-white min-h-screen text-gray-800">
        {children}
      </body>
    </html>
  )
}
// This is a basic layout file for a Next.js application.
// It sets up the HTML structure, imports global styles, and defines metadata for the site.
// The layout includes a gradient background and ensures the body has a minimum height of the screen.
// The metadata includes a title and description for SEO purposes.
// The layout is designed to be simple and clean, focusing on providing a good user experience with



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
